apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: automount-nfs-poc

images:
- name: quay.io/a13x22/toolbox-container
  newTag: basic

resources:
  # Security Context Constraints and RBAC
  - restricted-hostpath-scc.yaml
  - selinux-fix-scc.yaml
  - selinux-fix-sa.yaml
  - test-pod-sa.yaml
  - test-pod-scc-role.yaml
  - test-pod-scc-rolebinding.yaml
  # Network policy (optional hardening)
  - network-policy.yaml
  # Final working test deployment
  - test-pod-deploy-usera-live-nfs.yaml
