apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: selinux-fix-scc
  annotations:
    kubernetes.io/description: "SCC for fixing SELinux contexts on automount directories"
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- SYS_ADMIN
- DAC_OVERRIDE
- CHOWN
- FOWNER
- SETUID
- SETGID
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:automount-nfs-poc:selinux-fix-sa
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
- hostPath
