apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: automount-nfs-poc

configMapGenerator:
- name: ldap-bootstrap
  files:
  - bootstrap.ldif

resources:
- ldap-deploy.yaml
- ldap-svc.yaml
- ldap-sa.yaml
- ldap-scc-role.yaml
- ldap-scc-rolebinding.yaml

