apiVersion: v1
kind: Pod
metadata:
  name: selinux-test-userb-home
  namespace: automount-nfs-poc
spec:
  serviceAccountName: test-pod
  containers:
  - name: test
    image: quay.io/a13x22/toolbox-container:basic
    imagePullPolicy: Always
    workingDir: /tmp
    securityContext:
      runAsUser: 2002
      runAsGroup: 2002
    command: ["/bin/bash","-lc"]
    args:
      - |
        echo ready; sleep infinity
    volumeMounts:
    - name: host-home-all
      mountPath: /home
      mountPropagation: HostToContainer
  volumes:
  - name: host-home-all
    hostPath: { path: /var/mnt/home, type: Directory }